### ISSUE TITLE
[rossrv] "rossrv show" outputs error `No handlers could be found for logger "rosout"`

### ISSUE THREAD

**Issue by kejxu** [ms-iot/ROSOnWindows#13] opened 2018-10-10 23:46 UTC
when you use rossrv show to show message structure, it will output `No handlers could be found for logger "rosout"` in the very beginning.

**Comment by seanyen** [comment] 2020-02-04 23:36
I cannot reproduce this problem, so I am closing it.

**Closed by seanyen** 2020-02-04 23:36 UTC
Labels: bug
