### ISSUE TITLE
[MoveIt] UR3 build fails due to missing chainiksolver_pos_nr_jl_mimic.hpp

### ISSUE THREAD

**Issue by alecGraves** [ms-iot/ROSOnWindows#88] opened 2019-03-24 23:22 UTC
**Describe the bug**
Compiling universal_robot package fails because of missing moveit .hpp

```
fatal error C1083: Cannot open include file: 'moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp': No such file or directory
```

<details><summary> (click here) Full build log: </summary>
<p>

```
Base path: C:\Users\alec\Documents\moveit_tutorial_ws
Source space: C:\Users\alec\Documents\moveit_tutorial_ws\src
Build space: C:\Users\alec\Documents\moveit_tutorial_ws\build
Devel space: C:\Users\alec\Documents\moveit_tutorial_ws\devel
Install space: C:\Users\alec\Documents\moveit_tutorial_ws\install
####
#### Running command: "nmake cmake_check_build_system" in "C:\Users\alec\Documents\moveit_tutorial_ws\build"
####

Microsoft (R) Program Maintenance Utility Version 14.16.27024.1
Copyright (C) Microsoft Corporation.  All rights reserved.

####
#### Running command: "nmake" in "C:\Users\alec\Documents\moveit_tutorial_ws\build"
####

Microsoft (R) Program Maintenance Utility Version 14.16.27024.1
Copyright (C) Microsoft Corporation.  All rights reserved.

[  1%] Built target _setup_util.py_executable_install_python
[  1%] Built target _ur_msgs_generate_messages_check_deps_RobotStateRTMsg
[  1%] Built target _ur_msgs_generate_messages_check_deps_IOStates
[  1%] Built target _ur_msgs_generate_messages_check_deps_SetIO
[  1%] Built target _ur_msgs_generate_messages_check_deps_Digital
[  1%] Built target _ur_msgs_generate_messages_check_deps_MasterboardDataMsg
[  1%] Built target _ur_msgs_generate_messages_check_deps_SetPayload
[  1%] Built target _ur_msgs_generate_messages_check_deps_ToolDataMsg
[  1%] Built target std_msgs_generate_messages_cpp
[  1%] Built target _ur_msgs_generate_messages_check_deps_Analog
[ 11%] Built target ur_msgs_generate_messages_cpp
[ 11%] Built target std_msgs_generate_messages_py
[ 24%] Built target ur_msgs_generate_messages_py
[ 24%] Built target std_msgs_generate_messages_nodejs
[ 34%] Built target ur_msgs_generate_messages_nodejs
[ 34%] Built target std_msgs_generate_messages_eus
[ 45%] Built target ur_msgs_generate_messages_eus
[ 45%] Built target std_msgs_generate_messages_lisp
[ 55%] Built target ur_msgs_generate_messages_lisp
[ 55%] Built target ur_msgs_generate_messages
[ 56%] Built target ur_driver_gencfg
[ 78%] Built target ur_driver_common
[ 82%] Built target ur_hardware_interface
[ 82%] Built target geometry_msgs_generate_messages_py
[ 82%] Built target actionlib_generate_messages_cpp
[ 82%] Built target geometry_msgs_generate_messages_nodejs
[ 82%] Built target roscpp_generate_messages_eus
[ 82%] Built target actionlib_msgs_generate_messages_cpp
[ 82%] Built target roscpp_generate_messages_cpp
[ 82%] Built target rosgraph_msgs_generate_messages_eus
[ 82%] Built target rosgraph_msgs_generate_messages_nodejs
[ 82%] Built target roscpp_generate_messages_lisp
[ 82%] Built target geometry_msgs_generate_messages_eus
[ 82%] Built target trajectory_msgs_generate_messages_lisp
[ 82%] Built target rosgraph_msgs_generate_messages_cpp
[ 82%] Built target roscpp_generate_messages_py
[ 82%] Built target roscpp_generate_messages_nodejs
[ 82%] Built target rosgraph_msgs_generate_messages_lisp
[ 82%] Built target rosgraph_msgs_generate_messages_py
[ 82%] Built target sensor_msgs_generate_messages_py
[ 82%] Built target controller_manager_msgs_generate_messages_eus
[ 82%] Built target controller_manager_msgs_generate_messages_lisp
[ 82%] Built target control_msgs_generate_messages_py
[ 82%] Built target controller_manager_msgs_generate_messages_nodejs
[ 82%] Built target controller_manager_msgs_generate_messages_py
[ 82%] Built target controller_manager_msgs_generate_messages_cpp
[ 82%] Built target actionlib_generate_messages_eus
[ 82%] Built target actionlib_msgs_generate_messages_lisp
[ 82%] Built target actionlib_msgs_generate_messages_eus
[ 82%] Built target std_srvs_generate_messages_lisp
[ 82%] Built target sensor_msgs_generate_messages_eus
[ 82%] Built target actionlib_generate_messages_py
[ 82%] Built target actionlib_generate_messages_nodejs
[ 82%] Built target actionlib_generate_messages_lisp
[ 82%] Built target sensor_msgs_generate_messages_nodejs
[ 82%] Built target industrial_msgs_generate_messages_py
[ 82%] Built target industrial_msgs_generate_messages_lisp
[ 82%] Built target control_msgs_generate_messages_lisp
[ 82%] Built target sensor_msgs_generate_messages_cpp
[ 82%] Built target tf_generate_messages_eus
[ 82%] Built target geometry_msgs_generate_messages_lisp
[ 82%] Built target std_srvs_generate_messages_nodejs
[ 82%] Built target trajectory_msgs_generate_messages_eus
[ 82%] Built target trajectory_msgs_generate_messages_py
[ 82%] Built target trajectory_msgs_generate_messages_cpp
[ 82%] Built target trajectory_msgs_generate_messages_nodejs
[ 82%] Built target sensor_msgs_generate_messages_lisp
[ 82%] Built target control_msgs_generate_messages_eus
[ 82%] Built target control_msgs_generate_messages_cpp
[ 82%] Built target control_msgs_generate_messages_nodejs
[ 82%] Built target industrial_msgs_generate_messages_nodejs
[ 82%] Built target actionlib_msgs_generate_messages_py
[ 82%] Built target actionlib_msgs_generate_messages_nodejs
[ 82%] Built target geometry_msgs_generate_messages_cpp
[ 82%] Built target industrial_msgs_generate_messages_cpp
[ 82%] Built target tf_generate_messages_nodejs
[ 82%] Built target tf2_msgs_generate_messages_lisp
[ 82%] Built target industrial_msgs_generate_messages_eus
[ 82%] Built target std_srvs_generate_messages_py
[ 82%] Built target std_srvs_generate_messages_eus
[ 82%] Built target tf_generate_messages_py
[ 82%] Built target std_srvs_generate_messages_cpp
[ 82%] Built target tf2_msgs_generate_messages_nodejs
[ 82%] Built target tf2_msgs_generate_messages_cpp
[ 82%] Built target tf_generate_messages_cpp
[ 82%] Built target tf_generate_messages_lisp
[ 82%] Built target tf2_msgs_generate_messages_py
[ 82%] Built target tf2_msgs_generate_messages_eus
[ 84%] Built target ur_driver
[ 87%] Built target ur5_kin
[ 89%] Built target ur10_kin
[ 92%] Built target ur3_kin
[ 93%] Building CXX object universal_robot/ur_kinematics/CMakeFiles/ur3_moveit_plugin.dir/src/ur_moveit_plugin.cpp.obj
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
ur_moveit_plugin.cpp
Including header <class_loader/class_loader.h> is deprecated,
include <class_loader/class_loader.hpp> instead.
C:\Users\alec\Documents\moveit_tutorial_ws\src\universal_robot\ur_kinematics\include\ur_kinematics/ur_moveit_plugin.h(97): fatal error C1083: Cannot open include file: 'moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
Invoking "nmake" failed
```

</p>
</details>

**To Reproduce**
From the [UR3 Moveit tutorial](https://github.com/ms-iot/ROSOnWindows/blob/99251583b5aab2077b142ecdd3cfdec373d0d2bb/Moveit/UR3.md):

```
(open a command prompt as admin)
> choco upgrade ros-melodic-desktop_full -y
> choco upgrade ros-melodic-moveit -y
```
```
(open a command prompt as admin)
> c:\opt\ros\melodic\x64\setup.bat
> mkdir c:\catkin_ws\src
> cd c:\catkin_ws\src
> git clone https://github.com/ms-iot/universal_robot -b init_windows
> git clone https://github.com/ms-iot/ur_modern_driver -b init_windows
> cd c:\catkin_ws
> catkin_make
```

**Expected behavior**
The build succeeds

**Environment information:**
 - OS version: `Microsoft Windows Version 1803 (OS Build 17134.523)`
<details><summary> (click here) Chocolatey Versions: </summary>
<p>

```
>choco list --local-only
Chocolatey v0.10.11
assimp 4.0.1.1809242322
boost 1.66.0.1809242326
bullet3 2.87.0.1809242326
bzip2 1.0.6.1901242108
chocolatey 0.10.11
chocolatey-core.extension 1.3.3
chocolatey-windowsupdate.extension 1.0.3
clapack 3.2.1.1811082319
console_bridge 0.4.0.1809242322
cppunit 1.12.1.1809242322
cppzmq 4.2.2.1811162207
dlfcn-win32 1.1.1.1811162226
eigen 3.3.4.1809242322
freeglut 3.0.0.1809242322
freeimage 3.17.0.1811160037
gazebo9 9.4.1.1901022119
google-mock 1.8.0.1809242326
google-test 1.8.0.1809242322
gtk2 2.22.1.1809242322
hg 4.9
ilmbase 2.2.1.1811210800
jasper 2.0.14.1811210919
jxrlib 1.1.0.1811210809
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.4
KB3035131 1.0.2
lcms 2.8.0.1811210903
libccd 2.0.0.1809242322
libcurl 7.58.0.1809242322
libfcl 0.5.0.1809242322
libflann 1.9.1.1809090720
libglew 2.1.0.1809101757
libgraphviz 2.41.0.1810022039
libjpeg-turbo 1.2.1.201304081
liblzma 5.2.4.1811210837
libogg 1.3.3.1809090720
libompl 1.2.2.1809120057
libopencv 3.4.1.1809242322
libpcl 1.8.1.1809090720
libpng 1.6.35.1809242322
libqglviewer 2.7.1.1809090720
libqhull 2015.2.0.1809242322
libraw 0.19.0.1811210804
libtbb-dev 2018.6.0.1812011750
libtheora 1.1.1.1809090720
libwebp 0.6.1.1811210731
log4cxx 0.10.0.1809242322
lz4 1.8.1.1809242322
octomap 1.9.0.1809090720
ogre 1.10.11.1901312214
openblas 0.2.20.1811082312
openexr 2.2.1.1811210832
openjpeg 2.3.0.1811210736
openssl 1.1.1.1809242322
pkg-config 0.29.2.1809242322
poco 1.8.1.1809242322
protobuf 3.6.1.1811130545
pyqt5 5.10.1.1809242322
pyside2 5.10.1.1809242322
qt5-sdk 5.10.1.1810112239
qwt 6.1.3.1811212304
ros-catkin-tools 0.0.1.1901231908
ros-cmake 3.11.4.1809242322
ros-melodic-desktop_full 20190324.1
ros-melodic-moveit 20190324.1
ros-python2 2.7.15.1809242354
sbcl 0.0.0.1809242326
sdl 1.2.15.1809242322
sdl_image 1.2.12.1809242322
sip 4.19.8.1809242322
swig 3.0.12
tiff 4.0.9.1811210742
tinyxml 2.6.2.1809242322
tinyxml2 6.1.0.1809242322
urdfdom 1.0.0.1809242322
urdfdom_headers 1.0.0.1809242322
vcpython27 9.0.30729.1809090720
vcredist140 14.16.27027.1
yaml-cpp 0.6.2.1901170034
zeromq 4.2.5.1811162203
zlib 1.2.11.1809242322
83 packages installed.
```

</p>
</details>

**Comment by seanyen** [comment] 2019-03-25 00:18
@alecGraves Most likely it is caused by this recent [change](https://github.com/ros-industrial/universal_robot/commit/1f2a2b54c40c4bcadefb5f2f9ce52fc6cf1dc36a) not being rebased into https://github.com/ms-iot/universal_robot.

Can you try to remove those non-existent headers to see if it go through?

**Comment by alecGraves** [comment] 2019-03-25 01:59
Yep, that fixed it. Thanks!

**Comment by ooeygui** [comment] 2019-05-17 18:20
Closing since fixed :-)

**Closed by ooeygui** 2019-05-17 18:20 UTC
